// Catálogo inicial. Preços em centavos (R$ 189,90 = 18990). Ajuste à vontade
// aqui (antes do primeiro uso) ou depois pelo painel de administração.
export const catalog = [
  { slug: 'tambor-percussao', name: 'Tambor de percussão', category: 'Instrumentos', icon: 'drum', price_cents: 18990, stock: 8,
    description: 'Tambor com pele sintética afinável e corpo em madeira. Bom para iniciantes, rodas de samba e aulas de ritmo.' },
  { slug: 'tupperware', name: 'Tupperware', category: 'Cozinha e bar', icon: 'container', price_cents: 4990, stock: 40,
    description: 'Pote hermético com tampa de vedação. Vai à geladeira, ao freezer e ao micro-ondas (sem a tampa).' },
  { slug: 'mesa', name: 'Mesa', category: 'Móveis', icon: 'table', price_cents: 45990, stock: 5,
    description: 'Mesa de madeira maciça para 4 lugares, com acabamento em verniz fosco.' },
  { slug: 'banco', name: 'Banco', category: 'Bancos e pufs', icon: 'bench', price_cents: 12990, stock: 15,
    description: 'Banco comprido de madeira, firme e leve, para varanda, cozinha ou corredor.' },
  { slug: 'puf', name: 'Puf', category: 'Bancos e pufs', icon: 'pouf', price_cents: 14990, stock: 12,
    description: 'Puf estofado redondo, revestido em tecido resistente. Serve de assento ou apoio para os pés.' },
  { slug: 'copo', name: 'Copo', category: 'Cozinha e bar', icon: 'cup', price_cents: 1290, stock: 120,
    description: 'Copo de vidro liso de 350 ml, resistente para o uso diário.' },
  { slug: 'caneca', name: 'Caneca', category: 'Cozinha e bar', icon: 'mug', price_cents: 2990, stock: 60,
    description: 'Caneca de cerâmica de 300 ml para café, chá ou chocolate quente.' },
  { slug: 'cadeira', name: 'Cadeira', category: 'Móveis', icon: 'chair', price_cents: 21990, stock: 20,
    description: 'Cadeira de madeira com encosto anatômico, combina com a mesa da loja.' },
  { slug: 'mesa-de-plastico', name: 'Mesa de plástico', category: 'Móveis', icon: 'table-plastic', price_cents: 13990, stock: 25,
    description: 'Mesa de plástico reforçado, empilhável, para área externa, festas e bares.' },
  { slug: 'banco-madeira-alto', name: 'Banco de madeira alto', category: 'Bancos e pufs', icon: 'stool-tall', price_cents: 18990, stock: 14,
    description: 'Banqueta alta de madeira com apoio para os pés, na altura certa para balcões e bancadas.' },
  { slug: 'banco-madeira-baixo', name: 'Banco de madeira baixo', category: 'Bancos e pufs', icon: 'stool', price_cents: 9990, stock: 18,
    description: 'Banquinho baixo de madeira, para sentar, apoiar vasos ou alcançar o armário.' },
  { slug: 'puf-de-lata', name: 'Puf de lata', category: 'Bancos e pufs', icon: 'pouf-can', price_cents: 16990, stock: 10,
    description: 'Puf feito com lata reaproveitada, pintado à mão e com assento estofado.' },
  { slug: 'puf-de-tambor', name: 'Puf de tambor', category: 'Bancos e pufs', icon: 'pouf-drum', price_cents: 24990, stock: 7,
    description: 'Puf feito de tambor metálico reaproveitado, com assento estofado e pintura industrial.' },
  { slug: 'balde-de-gelo', name: 'Balde de gelo', category: 'Cozinha e bar', icon: 'bucket', price_cents: 7990, stock: 30,
    description: 'Balde de gelo em metal com alças, cabe até 6 garrafas long neck.' },
  { slug: 'caneca-de-aluminio', name: 'Caneca de alumínio', category: 'Cozinha e bar', icon: 'mug-metal', price_cents: 3490, stock: 50,
    description: 'Caneca de alumínio que mantém a bebida gelada por mais tempo. Ideal para chope e cerveja.' },
];
